// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function ConnectSerial(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectSerial'](arg1, arg2, arg3);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function LoadHosts() {
  return window['go']['main']['App']['LoadHosts']();
}

export function SaveHosts(arg1) {
  return window['go']['main']['App']['SaveHosts'](arg1);
}

export function SendData(arg1, arg2) {
  return window['go']['main']['App']['SendData'](arg1, arg2);
}
