// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ConnectSerial(arg1:string,arg2:string,arg3:number):Promise<string>;

export function Disconnect(arg1:string):Promise<void>;

export function GetSerialPorts():Promise<Array<string>>;

export function LoadHosts():Promise<string>;

export function SaveHosts(arg1:string):Promise<void>;

export function SendData(arg1:string,arg2:string):Promise<void>;
