// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4, arg5);
}

export function ConnectSerial(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectSerial'](arg1, arg2, arg3);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function GetSerialPorts() {
  return window['go']['main']['App']['GetSerialPorts']();
}

export function ImportSSHKeyFromFile() {
  return window['go']['main']['App']['ImportSSHKeyFromFile']();
}

export function ListDirectory(arg1, arg2) {
  return window['go']['main']['App']['ListDirectory'](arg1, arg2);
}

export function LoadHosts() {
  return window['go']['main']['App']['LoadHosts']();
}

export function LoadSSHKeys() {
  return window['go']['main']['App']['LoadSSHKeys']();
}

export function MakeDirectory(arg1, arg2) {
  return window['go']['main']['App']['MakeDirectory'](arg1, arg2);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2, arg3);
}

export function SaveHosts(arg1) {
  return window['go']['main']['App']['SaveHosts'](arg1);
}

export function SaveSSHKeys(arg1) {
  return window['go']['main']['App']['SaveSSHKeys'](arg1);
}

export function SendData(arg1, arg2) {
  return window['go']['main']['App']['SendData'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2, arg3);
}
