// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ConnectSerial(arg1:string,arg2:string,arg3:number):Promise<string>;

export function DeleteFile(arg1:string,arg2:string):Promise<string>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<string>;

export function GetSerialPorts():Promise<Array<string>>;

export function ImportSSHKeyFromFile():Promise<string>;

export function ListDirectory(arg1:string,arg2:string):Promise<string>;

export function LoadHosts():Promise<string>;

export function LoadSSHKeys():Promise<string>;

export function MakeDirectory(arg1:string,arg2:string):Promise<string>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveHosts(arg1:string):Promise<void>;

export function SaveSSHKeys(arg1:string):Promise<void>;

export function SendData(arg1:string,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<string>;
